// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ewslbT6NUPU73m_kfCW_R6fTztjmbDs',
    appId: '1:27780016152:web:cbdd94b1d760edd4c0fb6d',
    messagingSenderId: '27780016152',
    projectId: 'abacus-ext',
    authDomain: 'abacus-ext.firebaseapp.com',
    storageBucket: 'abacus-ext.appspot.com',
    measurementId: 'G-28B08M9WT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrgEcH28i1585fa_7GmCejZcCJ_jndNY',
    appId: '1:27780016152:android:748e05dd67197549c0fb6d',
    messagingSenderId: '27780016152',
    projectId: 'abacus-ext',
    storageBucket: 'abacus-ext.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6_woT6zSnPSpnMvhnIdZgnb1R4HGRXM',
    appId: '1:27780016152:ios:c28bd49d23aa70e3c0fb6d',
    messagingSenderId: '27780016152',
    projectId: 'abacus-ext',
    storageBucket: 'abacus-ext.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6_woT6zSnPSpnMvhnIdZgnb1R4HGRXM',
    appId: '1:27780016152:ios:c28bd49d23aa70e3c0fb6d',
    messagingSenderId: '27780016152',
    projectId: 'abacus-ext',
    storageBucket: 'abacus-ext.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ewslbT6NUPU73m_kfCW_R6fTztjmbDs',
    appId: '1:27780016152:web:404664ed375d17c5c0fb6d',
    messagingSenderId: '27780016152',
    projectId: 'abacus-ext',
    authDomain: 'abacus-ext.firebaseapp.com',
    storageBucket: 'abacus-ext.appspot.com',
    measurementId: 'G-QZWGC5XP74',
  );
}
